#!/bin/bash

# Create a new directory and enter it
md() {
	mkdir -p "$@" && cd "$@"
}

# cd into whatever is the forefront Finder window.
cdf() {  # short for cdfinder
  cd "`osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)'`"
}

# Copy w/ progress
cp_p () {
  rsync -WavP --human-readable --progress $1 $2
}